---
title: "Untitled"
author: "Maria Carrasco Melendez"
date: "10/20/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
datos_iris<-rename(iris,"Long_Sepalo"="Sepal.Length","Ancho_Sepalo"="Sepal.Width",'Long_Petalo'='Petal.Length','Ancho_Petalo'="Petal.Width", "Especie"="Species")
```


```{r cars}
library(rsample)
library(glmnet) 
library(dplyr)  
library(ggplot2)
library(nortest)
library(readr)
```



```{r}
library(datasets)
data(iris)
```

```{r}
setosa <- subset(datos_iris, Especie == "setosa")
versicolor <- subset(datos_iris, Especie == "versicolor")
virginica <- subset(datos_iris, Especie == "virginica")
```


```{r}
tapply(iris$Petal.Length,iris$Species,summary)
tapply(iris$Petal.Width,iris$Species,summary)
tapply(iris$Sepal.Length,iris$Species,summary)
tapply(iris$Sepal.Width,iris$Species,summary)
```


```{r}
cov(iris[,1:4])
```
```{r}
boxplot(x=iris[,1:4],main="Boxplots Iris")
```

```{r}
pairs(iris[,1:4],pch=as.numeric(iris$Species),col=iris$Species)
```
```

```{r}
summary(setosa)

summary (versicolor)

summary (virginica)
```

```{r}
#Grafica para petalo
ggplot(datos_iris, aes(Long_Petalo, Ancho_Petalo)) + 
  geom_point(aes(color = datos_iris$Especie), size = 3)

#Grafica para sepalo

ggplot(datos_iris, aes(Long_Sepalo, Ancho_Sepalo)) + 
  geom_point(aes(color = datos_iris$Especie), size = 3)
```

